### ISSUE TITLE
Cannot push local commit to Github

### ISSUE THREAD

**Issue by hollzzar** [psu-psychology/r-bootcamp-2019#35]
I made some small changes to the data_visualization.Rmd file on the desktop app, but it won't let me push my commits to GitHub because they contain an email address that's marked as private (I think Alicia's). I tried taking out the @ sign in her email as a workaround, but it still won't let me push to GitHub. Does anyone know how I can fix this issue? Thanks!

**Comment by michaelhallquist** [comment]
Not too sure -- could you post the command you're calling (git push?) and the error you're seeing?

**Comment by hollzzar** [comment]
Sure, the first one shows the suggestion to "push origin," and the second shows the error after I do that.

<img width="648" alt="Screen Shot 2019-08-22 at 11 17 24 PM" src="https://user-images.githubusercontent.com/15241450/63564433-0df9f600-c533-11e9-8a20-655c2387957e.png">
<img width="641" alt="Screen Shot 2019-08-22 at 11 17 32 PM" src="https://user-images.githubusercontent.com/15241450/63564434-0df9f600-c533-11e9-988a-08a10b50c395.png">

**Comment by michaelhallquist** [comment]
Huh, yeah, I wonder if the suggestion below might help. Is it possible it's due to your own email settings in Github?

"You're likely pushing a commit that is signed using your email address, and in your settings on Github. You can change this behavior by either going to github -> settings -> email and unchecking the box that says Block command line pushes that expose my email, make your email not private (right above that option), or sign your commits with a public email."

https://github.com/desktop/desktop/issues/5639

Hope this solves it...
Michael

**Comment by hollzzar** [comment]
Okay yes that worked thank you! I didn't realize it was my email that was the issue. I was able to send the push.

**Comment by michaelhallquist** [comment]
Great, glad that worked!

-M
